# Generated by Django 4.2.3 on 2023-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(blank=True, null=True, verbose_name='Product Name'),
        ),
    ]
