version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: postgres
      POSTGRES_DB: venturas-crawler-db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        ./entrypoint.sh
        python manage.py runserver 0.0.0.0:8080
    restart: always
    volumes:
      - .:/home/code
    links:
      - db:db
    ports:
      - "8080:8080"
    env_file:
      - ./conf/settings/.env
    environment:
      DB_HOST: 'db'
    depends_on:
      - db

volumes:
  postgres_data: